# Default Traditional Chinese language file

# Which version of Skript this language file was written for
version: @version@

# What null (nothing) should show up as in a string/text
none: <none>

# -- Skript --
skript:
	copyright: ~ © Peter Güttinger aka Njol 製作 ~
	prefix: <gray>[<gold>Skript<gray>] <reset>
	quotes error: 引號(")使用無效。如果你想在已處於引號內的文字再次使用引號，請同時使用兩個，就像這樣：""
	brackets error: 括號數量或位置無效。請確保每個左括號都有對應的右括號。
	invalid reload: Skript 只可以透過 Bukkit 的 "/reload" 或 Skript 的 "/skript reload" 重新載入。
	no scripts: 找不到任何腳本，或許你應該寫一些 ;)
	no errors: 已成功無誤地加載了全部腳本。
  scripts loaded: 已載入了%s個腳本，總共包含了%s個結構 (耗時%s) 
	finished loading: 已完成載入。
  warning message: /reload 或另一個插件重新啟動了 Skript。 Skript 並不支援此行為，並可能會因而發生問題。
	restart message: 請考慮以重新啟動伺服器取代此行為。
 
# -- Skript command --
skript command:
	usage: 用法:
	help:
		description: Skript的主要指令
		help: 顯示此幫助訊息。運行 "/skript reload/enable/disable/update" 以獲取更多資訊。
		reload:
			description: 重新載入某一個或全部腳本/設定檔/所有內容
			all: 重新載入主要設定檔、所有alias設定檔及全部腳本
			config: 重新載入主要設定檔
			aliases: 重新載入所有alias的設定檔（例如：aliases-english.zip/插件.jar）
			scripts: 重新載入所有腳本
			<script>: 重新載入某一個腳本/一個檔案內的所有腳本
		enable:
			description: 啟用某一個/全部腳本
			all: 啟用所有腳本
			<script>: 啟用某一個腳本/一個檔案內的所有腳本
		disable:
			description: 停用某一個/全部腳本
			all: 停用所有腳本
			<script>: 停用某一個腳本/一個檔案內的所有腳本
		update:
			description: 檢查更新或閱讀更新日誌
			check: 檢查是否處於最新版本
			changes: 列出由目前版本以來的的所有變更
		list: 列出所有已啟用/已停用的腳本
		info: 顯示 Skript alias/開發文檔的連結
    gen-docs: 利用插件資料夾內的文件/模板生成一個開發文檔
		test: 內部測試專用

	invalid script: 無法在scripts文件夾中找到腳本 <grey>"<gold>%s<grey>"<red>!
	invalid folder: 無法在scripts文件夾中找到資料夾 <grey>"<gold>%s<grey>"<red>!
	reload:
		warning line info: <gold><bold>第%s行:<gray> (%s)<reset>\n
		error line info: <light red><bold>第%s行:<gray> (%s)<reset>\n
		reloading: 正在重新載入中<gold>%s<reset>...
		reloaded: <gold>%s<lime>重新載入完成。 <gray>(<gold>%2$sms<gray>)
		player reload: <lime>%s <reset>正在重新載入中<gold>%s<reset>...
  	error: <light red>在重新載入<gold>%1$s<light red>時發生了<gold>%2$s<light red>個錯誤!<gray>（<gold>%3$sms<gray>）
		script disabled: <gold>%s<reset> 已被停用。 運行 <gray>/<gold>skript <cyan>enable <red>%s<reset>以啟用它。
		warning details: <yellow>    %s<reset>\n
		error details: <light red>    %s<reset>\n
		other details: <white>    %s<reset>\n
		line details: <gold>    行數: <gray>%s<reset>\n <reset>

		config, aliases and scripts: 主要設定檔、所有alias、以及所有腳本
		scripts: 所有腳本
		main config: 主要設定檔
		aliases: 所有alias
		script: <gold>%s<reset>
		scripts in folder: <gold>%s<reset> 中的所有腳本
  	x scripts in folder success: <gold>%1$s<reset> 中的 <gold>%2$s <lime>個腳本
		x scripts in folder error: <gold>%1$s<reset> 中的 <gold>%2$s <light red>個腳本
		empty folder: <gold>%s<reset> 檔案夾內沒有任何已啟用的腳本。
	enable:
		all:
			enabling: 正在啟用所有已停用的腳本...
			enabled: 已成功啟用並解析了所有已停用的腳本。
			error: <light red>在解析已禁用的腳本時發生了 <gold>%s <light red>個錯誤!
			io error: <light red>無法載入一個或多個腳本 - 某些腳本可能已被重新命名，並會在伺服器重新啟動後啟用: <gold>%s
		single:
			already enabled: <gold>%s<reset> 本來就啟動了! 如果檔案有任何變更，請運行 <gray>/<gold>skript <cyan>reload <red>%s<reset> 以重新載入它。
			enabling: 正在啟用中 <gold>%s<reset>...
			enabled: 已成功啟用並解析了 <gold>%s<reset>.
      error: <light red>在解析 <gold>%1$s<light red> 時發生了 <gold>%2$s <light red>個錯誤!
			io error: <light red>無法啟用 <gold>%s<light red>: <gold>%s
		folder:
			empty: <gold>%s<reset> 檔案夾內沒有任何已停用的腳本。
			enabling: Enabling <gold>%2$s <reset>script¦¦s¦ in <gold>%1$s<reset>...
			enabled: Successfully enabled & parsed <gold>%2$s<reset> previously disabled scripts in <gold>%1$s<reset>.
			error: <light red>Encountered <gold>%2$s <light red>error¦¦s¦ while parsing scripts in <gold>%1$s<light red>!
			io error: <light red>Error while enabling one or more scripts in <gold>%s <light red>(some scripts might get enabled when the server restarts): <gold>%s
	disable:
		all:
			disabled: 已成功停用所有腳本。
			io error: <light red>Could not rename one or more scripts - some scripts might have been renamed already and will be disabled when the server restarts: <gold>%s
		single:
			already disabled: <gold>%s<reset> is already disabled!
			disabled: Successfully disabled <gold>%s<reset>.
			io error: <light red>Could not rename <gold>%s<light red>, it will be enabled again when you restart the server: <gold>%s
		folder:
			empty: <gold>%s<reset> does not contain any enabled scripts.
			disabled: Successfully disabled <gold>%2$s<reset> script(s) in <gold>%1$s<reset>.
			io error: <light red>Could not disable one or more scripts in <gold>%s <light red>(some scripts might get disabled when the server restarts): <gold>%s
	update:
		# check/download: see Updater
		changes:
			# multiple versions:
			# 	title: <gold>%s<r> update¦ has¦s have¦ been released since this version (<gold>%s<r>) of Skript:
			# 	footer: To show the changelog of a version type <gold>/skript update changes <version><reset>
			# invalid version: No changelog for the version <gold>%s<red> available
			title: <bold><cyan>%s<reset> (%s)
			next page: <grey>page %s of %s. Type <gold>/skript update changes %s<gray> for the next page (hint: use the up arrow key)
	list:
		enabled:
			header: <white>Enabled scripts:
			element: <lime green>  %s
		disabled:
			header: <white>Disabled scripts:
			element: <light red>  %s
	info:
		aliases: Skript's aliases can be found here: <aqua>https://github.com/SkriptLang/skript-aliases
		documentation: Skript's documentation can be found here: <aqua>https://docs.skriptlang.org/
		tutorials: Skript's tutorials can be found here: <aqua>https://docs.skriptlang.org/tutorials
		version: Skript Version: <aqua>%s
		server: Server Version: <aqua>%s
		addons: Installed Skript Addons: <aqua>%s
		dependencies: Installed dependencies: <aqua>%s

# -- Log Messages --
log:
	# runtime errors
	runtime:
		error: <light red>The script '<gray>%s<light red>' encountered an error while executing the '<gray>%s<light red>' %s<light red>:\n
		errors skipped: <gold>%d<light red> runtime error[s] were thrown but not printed in the last frame. From: <gray>%s
		errors timed out: <gold>Line %d<light red> of script '<gray>%s<light red>' produced too many runtime errors (<gray>%d<light red> allowed per frame). No errors from this line will be printed for %d frames.
		error notification: <light red>Script '<gray>%s<light red>' produced runtime errors. Please check console logs for details.
		error notification plural: <light red>Script '<gray>%s<light red>' and %d others produced runtime errors. Please check console logs for details.

		warning: <yellow>The script '<gray>%s<yellow>' encountered a warning while executing the '<gray>%s<yellow>' %s<yellow>:\n
		warnings skipped: <yellow>%d<yellow> runtime warning[s] were thrown but not printed in the last frame. From: <gray>%s
		warnings timed out: <gold>Line %d<yellow> of script '<gray>%s<yellow>' produced too many runtime warnings (<gray>%d<yellow> allowed per frame). No warnings from this line will be printed for %d frames.
		warning notification: <yellow>Script '<gray>%s<yellow>' produced runtime warnings. Please check console logs for details.
		warning notification plural: <gold>Script '<gray>%s<yellow>' and %d others produced runtime warnings. Please check console logs for details.

		line info: <gold>    Line %s<white>: <gray>%s\n \n


# -- Updater --
updater:
	not started: Skript has not yet checked for the latest version. Use <gold>/skript update check<reset> to do so.
	checking: Checking for the latest version of Skript...
	check in progress: Checking for a new version is currently in progress.
	updater disabled: The updater is disabled, so a check for the latest version of Skript was not performed.
	check error: <red>There was an error checking for the latest version of Skript:<light red> %s
	running latest version: You're currently running the latest stable version of Skript.
	running latest version (beta): You're currently running a <i>beta<r> version of Skript, and no new <i>stable<r> version is available. Please note that you have to update to newer beta versions manually!
	update available: A new version of Skript is available: <gold>%s<reset> (you're currently running <gold>%s<reset>)
	downloading: Downloading Skript <gold>%s<reset>...
	download in progress: The latest version of Skript is currently being downloaded.
	download error: <red>There was an error downloading the latest version of Skript:<light red> %s
	downloaded: The latest version of Skript has been downloaded! Restart the server or use /reload to apply the changes.
	internal error: An internal error occurred while checking for the latest version of Skript. Please refer to the server log for details.
	custom version: You're currently running a custom Skript version. No updates will be automatically installed.
	nightly build: You're currently running a development build of Skript. No updates will be automatically installed.

# -- Commands --
commands:
	no permission message: You don't have the required permission to use this command
	cooldown message: You are using this command too often, please try again later
	executable by players: This command can only be used by players
	executable by console: This command can only be used by the console
	correct usage: Correct usage:
	invalid argument: Invalid argument <gray>'%s<gray>'<reset>. Allowed are:
	too many arguments: This command can only accept a single %2$s.
	internal error: An internal error occurred while attempting to perform this command.
	no player starts with: There is no player online whose name starts with '%s'
	multiple players start with: There are several players online whose names start with '%s'

# -- Hooks --
hooks:
	hooked: 成功與%s連接
	error: 無法連接至%1$s。這可能是因為 Skript 不支援已安裝的 %1$s 插件或該版本

# -- Aliases --
aliases:
	# Errors and warnings
	empty string: “”不是一個物品類型
	invalid item type: “%s” 不是一個物品類型
	empty name: 一個alias必須擁有名稱
	brackets error: 括號使用無效
	not enough brackets: 由字元 %s ('%s') 打開的括號必須閉合
	too many brackets: 字元 %s ('%s') 閉合了一個不存在的部分
	unknown variation: 變數 %s has not been defined before
	missing aliases: 以下的 Minecraft ID 都沒有任何 alias:
	empty alias: Alias has no Minecraft id or tags defined
	invalid minecraft id: Minecraft ID %s 無效
	useless variation: 此變數未指定任何的 Minecraft ID 或標籤, 所以並沒有用
	invalid tags: Specified tags are not defined in valid JSON指定的標籤未在有效的 JSON 中定義
	unexpected section: Sections are not allowed here
	invalid variation section: A section should be variation section, but %s is not valid variation name
	outside section: Aliases must be put in sections

	# Other messages
	loaded x aliases from: 已成功載入了%s個英文alias (來源:%s)
	loaded x aliases: 總共載入了%s個英文alias

# -- Time --
time:
	errors:
		24 hours: 一天只有24個小時
		12 hours: 使用12小時制不可以超出12點
		60 minutes: 一個小時只有60分鐘

# -- IO Exceptions --
io exceptions:
	unknownhostexception: 無法連接至%s
	accessdeniedexception: %s已拒絕存取要求
